$modelname "props_map_editor/bee2/aneonen/timer_indicator3.mdl"

$bodygroup "Body"
{
	studio "bee2_block_quarter_tile_3.smd"
}

$surfaceprop "metalpanel"

$contents "solid"

$illumposition -16 0 -31.95

$cdmaterials "bee2\models\props_map_editor\aneonen\"

$cbox 0 0 0 0 0 0

$bbox -16 -32 -63.9 16 0 0

$definebone "root" "" 0 0 0 0 0 0 0 0 0 0 0 0


$sequence "ref" {
	"bee2_block_quarter_tile_3.smd"
}
